services:
    numahop-mariadb:
        image: mariadb:10.10
        volumes:
            - numahop-mariadb:/var/lib/mysql
        networks:
            - numahop
        ports:
            - "3306:3306"
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: yes
            MARIADB_DATABASE: numahop
            MARIADB_USER: numahop
            MARIADB_PASSWORD: numahop
    numahop-elasticsearch:
        image: elasticsearch:2.4.6
        volumes:
            - numahop-elasticsearch:/usr/share/elasticsearch/data
        networks:
            - numahop
        ports:
            - "9209:9200"
            - "9309:9300"
        ulimits:
            nofile: 65536
        environment:
            ES_JAVA_OPTS: -Xms1500m -Xmx1500m -Des.cluster.name=pgcn
            discovery.type: single-node
        mem_limit: 2g
    numahop-mail:
        image: namshi/smtp
        networks:
            - numahop

networks:
    numahop:
volumes:
    numahop-mariadb:
    numahop-elasticsearch:
