# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: false
security.basic.enabled: false
management.context-path: /actuator
management.health.mail.enabled: false

server:
    port: 8080
    session.timeout: 10800  # 3 heures
    compression:
        enabled: true

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints:
    dump.id: threaddump #Pour Monilone
    jolokia.enabled: false
    logfile.external-file: ${logging.file}.log

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: $$$$_!!change_me!!_$$$$

instance:
    libraries: library_bibliotheque
    # library_identifier1, library_identifier2, etc..

info:
    app:
        name: "@project.name@"
        description: "@project.description@"
        version: "@project.version@"
    build:
        artifact: "@project.artifactId@"
        name: "@project.name@"
        description: "@project.description@"
        version: "@project.version@"

async:
    corePoolSize: 2
    maxPoolSize: 10
    queueCapacity: 10000

liquibase.change-log: classpath:config/liquibase/master.xml

spring:

    datasource:
        url: jdbc:mariadb://localhost:3306/pgcn?cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&characterEncoding=utf8&useUnicode=true
        username:
        password:
        hikari:
            auto-commit: false
            minimum-idle: 5
            maximum-pool-size: 20
            leak-detection-threshold: 600000

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        open-in-view: false
        show-sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: validate
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                connection.provider_disables_autocommit: true
                generate_statistics: false
                default_batch_fetch_size: 64
                order_inserts: false
                order_updates: false
                jdbc:
                    batch_size: 64
                    fetch_size: 384
                    batch_versioned_data: true
                temp:
                    use_jdbc_metadata_defaults: false
                cache:
                    use_second_level_cache: true
                    use_query_cache: false
                    region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    data:
        elasticsearch:
            cluster-nodes: localhost:9300
            cluster-name: pgcn
            properties:
                node:
                    name: Transport Client
            repositories:
                enabled: true

    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        activated: false
        from: contact-numahop@progilone.fr

    messageSource:
        cacheSeconds: 1

    jackson:
        serialization:
            # use_equality_for_object_id: true
            USE_EQUALITY_FOR_OBJECT_ID: true
            # write_dates_as_timestamps: false
            WRITE_DATES_AS_TIMESTAMPS: false
            # write_empty_json_arrays: true
            WRITE_EMPTY_JSON_ARRAYS: true

    # Gestion des upload (taille max)
    http:
        multipart:
            file-size-threshold: 10MB
            maxFileSize: 100MB
            maxRequestSize: 200MB

cache: # Cache configuration
    ehcache: # Ehcache configuration
        time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
        max-entries: 1000 # Number of objects in each cache entry

storage:
    binaries:
    digest: MD5
    depth: 3

export:
    rdf:
        default_uri: http://numahop.fr/
    ssh:
        knownHosts:
        strictHostKeyChecking: yes
    sftp:
        privateKey: /opt/pgcn/config/id_rsa

metrics:
    jmx.enabled: true

logging:
    file:
    warnDuration: 1500

sshForwarding:
    enabled: false
    server:
    user:
    password:
    port: 22
    knownHosts: /opt/pgcn/config/known_hosts
    strictHostKeyChecking: yes
    database:
        remoteServer: localhost
        localPort: 3306
        remotePort: 3306
    elasticsearch:
        remoteServer: localhost
        localPort: 9300
        remotePort: 9300

images:
    format:
        default:
           thumbHeight: 150
           thumbWidth:  150
           viewHeight:  1417
           viewWidth:   982
           printHeight: 2835
           printWidth:  1964

elasticsearch:
    bulk_size: 500
    index:
        name: pgcn

report:
    imagePath: images

# Services externes
services:
    cines:
        updating:
            cronenabled: false

cron:
    removeOldTokens: 0 0 0 * * ?
    cleanLocks: 0 30 0 * * *
    rebuildIndex: 0 40 0 * * *
    cleanDeliveryFiles: 0 0 1 * * ?
    cinesExport: 0 30 1 * * ?
    localExport: 0 0 4 * * ?
    cleanTemporaryFiles: 0 0 2 * * ?
    internetArchiveExport: 0 26 17 * * ?
    gestDeliveredFiles: 0 00 18 * * SAT
    cinesUpdateStatus: 0 10 * * * *
    omekaExport: 0 0 3 * * ?
    cleanExportCaches: 0 30 6 * * ?
    docUnitUpdateArk: 0 0 6 * * ?
    digitalLibraryExport: 0 0 3 * * ?

admin:
    login: admin
    password: $2a$10$xsRQ/2khgr0sblEfy6SjTujCnI3jGxj6q.yNQkKKaz4.ZIsuBT05O
    # default pwd = password - override on each server conf!!!
