imageMagick:
    convert: /usr/bin/convert
    identify: /usr/bin/identify

exifTool:
    process: /usr/bin/exiftool
    quot_char: ''

tesseract:
    process: /usr/bin/tesseract

nativeLibraries:
    path: /opt/svcmgmt/lib

crypto:
    password: PhoOpJaiCwy3Jos
    salt: POEvsixIf+LyzBkDpEsM5ngX8+mLNbGJDLpPlqhgrGw=
