server:
    port: 8080

spring:
    profiles: dev

    data:
        elasticsearch:
            cluster-nodes: localhost:9300
            cluster-name: pgcn
            properties:
                node:
                    name: Transport Client
            repositories:
                enabled: true

    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/pgcn
        username: pgcn
        password: pgcnpgcn
        maximumPoolSize: 20
        leakDetectionThreshold: 30000

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show_sql: false
        open-in-view: false
        generate-ddl: true
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate:
                generate_statistics: false
                default_batch_fetch_size: 64
                order_inserts: false
                order_updates: false
                jdbc:
                    batch_size: 64
                    fetch_size: 384
                    batch_versioned_data: true
                temp:
                    use_jdbc_metadata_defaults: false
                cache:
                    use_second_level_cache: true
                    use_query_cache: false
                    region.factory_class: fr.progilone.pgcn.config.jcache.NoDefaultJCacheRegionFactory

    mail:
        host: reverse.progilone.lan
        baseUrl: http://localhost:8080

cache: # Cache configuration
    ehcache: # Ehcache configuration
        time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
        max-entries: 1000 # Number of objects in each cache entry

logging:
    file: log/numahop
    warnDuration: 1500

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

storage:
    binaries: C://Temp/pgcn/Repository
    digest: MD5
    depth: 3
    
imageMagick:
    convert: C://Program Files/ImageMagick/convert.exe
    identify: C://Program Files/ImageMagick/identify.exe
    
exifTool:
    process: C://Windows/exiftool.exe
    quot_char: "\""
    
tesseract:
    process: C:\Program Files (x86)\Tesseract-OCR\tesseract.exe    

images:
    format:
        default:
           thumbHeight: 150
           thumbWidth:  150
           viewHeight:  1417
           viewWidth:   982
           printHeight: 2835
           printWidth:  1964
    
nativeLibraries:
    path: C://Program Files/YAZ/bin

uploadPath:
    condition_report: C://Temp/pgcn/upload/condition_report
    ead: C://Temp/pgcn/upload/ead
    import: C://Temp/pgcn/upload/import
    library: C://Temp/pgcn/upload/library
    user: C://Temp/pgcn/upload/user
    template: C://Temp/pgcn/upload/templates

export:
    rdf:
        default_uri: http://numahop.fr/
    ssh:
        knownHosts: src/main/resources/config/app/known_hosts-dev
        strictHostKeyChecking: yes

sshForwarding:
    enabled: false
    server:
    user:
    password:
    port: 22
    knownHosts: /opt/pgcn/config/known_hosts
    strictHostKeyChecking: yes
    database:
        remoteServer: localhost
        localPort: 3306
        remotePort: 3306
    elasticsearch:
        remoteServer: localhost
        localPort: 9300
        remotePort: 9300

crypto:
    password: PhoOpJaiCwy3Jos
    salt: POEvsixIf+LyzBkDpEsM5ngX8+mLNbGJDLpPlqhgrGw=  

# Services externes
services:
    cines:
        updating:
            cronenabled: false
        aip: C://Temp/pgcn/cines/aip
        cache: C://Temp/pgcn/cines/cache
        facile: https://facile.cines.fr/xml
        xsd:
           sip: src/main/resources/config/xsd/sip.xsd
    archive:
        alto: C://Temp/pgcn/archive/alto   
    metaDatas :
        path: C://Temp/pgcn/metadatas
    deliveryreporting :
        path: C://Temp/pgcn/deliveryReporting
    omeka:
        cache: C://Temp/pgcn/omeka/cache
    ftpexport:
        cache: C://Temp/pgcn/ftpexport/cache
    
admin:
    login: admin
    password: $2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC
    