version: '3.8'
services:
    kibana8:
        image: docker.elastic.co/kibana/kibana:8.6.1
        environment:
            ELASTICSEARCH_HOSTS: '["http://numahop-elasticsearch8-1-1:9200"]'
        ports:
            - 127.0.0.1:5601:5601
