services:
    numahop-app:
        image: numahop
        volumes:
            - numahop-data:/opt/pgcn/
        networks:
            - numahop
        ports:
            - "8080:8080"
            - "8000:8000"
        environment:
            _JAVA_OPTIONS: -Xmx512m -Xms16m -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
            SPRING_PROFILES_ACTIVE: prod
            SPRING_DATASOURCE_URL: jdbc:mariadb://numahop-mariadb:3306/numahop
            SPRING_DATASOURCE_USERNAME: numahop
            SPRING_DATASOURCE_PASSWORD: numahop
            SPRING_ELASTICSEARCH_URIS: http://numahop-elasticsearch:9200
            SPRING_MAIL_HOST: numahop-mail
            SPRING_MAIL_ACTIVATED: true
networks:
    numahop:
volumes:
    numahop-data:
